version: '2'
services:

  factorio:
    image: dtandersen/factorio:latest
    ports:
      - "34197:34197/udp"
      - "27015:27015/udp"
    volumes:
      - ./game-data:/factorio
    restart: always
